# Elasticsearch Configuration v8.9.0
# Project X Rental Platform - Production Configuration

#----------------------
# Cluster Configuration
#----------------------
cluster.name: projectx-elasticsearch
cluster.initial_master_nodes: ["${HOSTNAME}"]
discovery.seed_hosts: ["elasticsearch"]
discovery.type: single-node
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: "85%"
cluster.routing.allocation.disk.watermark.high: "90%"
cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.enable: all
cluster.max_shards_per_node: 1000

#----------------------
# Node Configuration
#----------------------
node.name: ${HOSTNAME}
node.master: true
node.data: true
node.ingest: true
node.max_local_storage_nodes: 1
node.attr.zone: ${ZONE}
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
processors: 8

#----------------------
# Network Configuration
#----------------------
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300
http.cors.enabled: true
http.cors.allow-origin: "https://*.projectx.com"
http.cors.allow-credentials: true
http.cors.allow-methods: "OPTIONS,HEAD,GET,POST,PUT,DELETE"
http.max_content_length: "100mb"
http.compression: true

#----------------------
# Security Configuration
#----------------------
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
xpack.security.audit.enabled: true
xpack.security.audit.logfile.events.include: ["authentication_success", "authentication_failure", "access_denied", "connection_denied"]
xpack.security.authc.api_key.enabled: true
xpack.security.authc.token.enabled: true
xpack.security.authc.realms.native.native1.order: 0

#----------------------
# Monitoring Configuration
#----------------------
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true
xpack.monitoring.collection.interval: "10s"
xpack.monitoring.history.duration: "7d"
xpack.monitoring.collection.cluster.stats.timeout: "10s"
xpack.monitoring.collection.node.stats.timeout: "10s"
xpack.monitoring.collection.index.stats.timeout: "10s"
xpack.monitoring.exporters.local.type: local
xpack.monitoring.exporters.local.use_ingest: false

#----------------------
# Memory Configuration
#----------------------
bootstrap.memory_lock: true
indices.memory.index_buffer_size: "30%"
indices.queries.cache.size: "5%"
indices.fielddata.cache.size: "20%"
indices.breaker.total.use_real_memory: true
indices.breaker.request.limit: "60%"
indices.breaker.fielddata.limit: "40%"

#----------------------
# Index Configuration
#----------------------
index.number_of_shards: 1
index.number_of_replicas: 1
index.refresh_interval: "1s"
index.max_result_window: 10000
index.mapping.total_fields.limit: 2000
index.mapping.depth.limit: 20
index.blocks.read_only_allow_delete: null
action.destructive_requires_name: true
action.auto_create_index: false