apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: rental-platform
  labels:
    app: rental-platform
    component: database
    environment: production
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "database"
    vault.hashicorp.com/agent-pre-populate-only: "true"
type: Opaque
stringData:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_SSL_CERT: "${POSTGRES_SSL_CERT}"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: rental-platform
  labels:
    app: rental-platform
    component: auth
    environment: production
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "auth"
    vault.hashicorp.com/agent-pre-populate-only: "true"
type: Opaque
stringData:
  JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
  JWT_PUBLIC_KEY: "${JWT_PUBLIC_KEY}"
  JWT_KEY_PASSPHRASE: "${JWT_KEY_PASSPHRASE}"
  OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
  OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
  MFA_ENCRYPTION_KEY: "${MFA_ENCRYPTION_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: rental-platform
  labels:
    app: rental-platform
    component: payment
    environment: production
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "payment"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    pci-dss.compliance/level: "1"
type: Opaque
stringData:
  STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
  STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
  STRIPE_ENDPOINT_SECRET: "${STRIPE_ENDPOINT_SECRET}"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
  namespace: rental-platform
  labels:
    app: rental-platform
    component: notification
    environment: production
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "notification"
    vault.hashicorp.com/agent-pre-populate-only: "true"
type: Opaque
stringData:
  SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
  TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
  TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
  TWILIO_VERIFY_SERVICE_SID: "${TWILIO_VERIFY_SERVICE_SID}"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: rental-platform
  labels:
    app: rental-platform
    component: cache
    environment: production
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "cache"
    vault.hashicorp.com/agent-pre-populate-only: "true"
type: Opaque
stringData:
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  REDIS_TLS_CERT: "${REDIS_TLS_CERT}"
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secrets
  namespace: rental-platform
  labels:
    app: rental-platform
    component: search
    environment: production
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "search"
    vault.hashicorp.com/agent-pre-populate-only: "true"
type: Opaque
stringData:
  ELASTIC_PASSWORD: "${ELASTIC_PASSWORD}"
  ELASTIC_USERNAME: "${ELASTIC_USERNAME}"
  ELASTIC_CA_CERT: "${ELASTIC_CA_CERT}"