# Prometheus Recording Rules Configuration v2.45.0
# Pre-computes frequently used metrics for efficient querying and alerting

groups:
  # Infrastructure resource utilization metrics
  - name: node_resource_utilization
    interval: 30s
    rules:
      # Average CPU utilization over 5m
      - record: instance:node_cpu_utilization:avg5m
        expr: |
          1 - avg by(instance) (rate(node_cpu_seconds_total{mode='idle'}[5m]))
      
      # Memory utilization percentage
      - record: instance:node_memory_utilization:avg5m
        expr: |
          1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)
      
      # Filesystem free space ratio
      - record: instance:node_filesystem_free:ratio
        expr: |
          node_filesystem_free_bytes{mountpoint='/'} / node_filesystem_size_bytes{mountpoint='/'}

  # API performance and reliability metrics
  - name: api_metrics
    interval: 30s
    rules:
      # Error rate calculation over 5m
      - record: api_error_rate:5m
        expr: |
          sum(rate(http_requests_total{status=~'5..'}[5m])) / sum(rate(http_requests_total[5m]))
      
      # 95th percentile latency over 5m
      - record: service:latency:p95:5m
        expr: |
          histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))
      
      # Service availability over 5m
      - record: service:availability:5m
        expr: |
          avg_over_time(up[5m])

  # Business KPI metrics
  - name: business_metrics
    interval: 1m
    rules:
      # Application conversion rate over 1h
      - record: application_conversion_rate:1h
        expr: |
          sum(increase(applications_completed_total[1h])) / sum(increase(applications_started_total[1h]))
      
      # Payment transaction volume over 1h
      - record: payment_transaction_volume:1h
        expr: |
          sum(increase(payment_amount_total[1h]))
      
      # Active users over 24h
      - record: active_users:24h
        expr: |
          count(count_over_time(user_activity_total[24h]))